# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee02d7ec246c6e670b98da9200fff2abdef1f3e8acb4935e4ac102f815e830b181bdef1c9383fc9ea78cf82b19f33c6d6f33984a87d92595bb2758584cc653a7

test:
  secret_key_base: 4376fc7efeaa6f3d2b33bf4b6fc162913c4a9b573f7f6796f3084e3043272bcbbdb150fa4d037ca91dfe25bec3d39ad525a2a4a70768428ef931cf061c80bd0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
